// Code generated by structmap; DO NOT EDIT.
package mapping

import (
	ref2 "github.com/dkowalsky92/structmap/examples/complex/models1"
	ref3 "github.com/dkowalsky92/structmap/examples/complex/models2"
	ref1 "github.com/google/uuid"
)

// MapUserToUserDTO copies User → UserDTO
func MapUserToUserDTO(src ref2.User, about *string) (dst ref3.UserDTO) {
	dst.Hobbies = src.Hobbies
	dst.Interests = src.Interests
	dst.ID = src.ID.String()
	dst.Name = &src.FirstName
	// no matching source found for field: LastName, consider adding an additional arg or aligning the fields
	dst.Age = src.Age
	dst.Height = &src.UserHeight
	dst.About = about
	dst.AdditionalProperties = src.AdditionalProperties
	return
}

// MapUserDTOToUser copies UserDTO → User
func MapUserDTOToUser(src ref3.UserDTO) (dst ref2.User, err error) {
	dst.Hobbies = src.Hobbies
	dst.Interests = src.Interests
	dst.ID, err = ref1.Parse(src.ID)
	dst.FirstName = *src.Name
	dst.Age = src.Age
	dst.UserHeight = *src.Height
	dst.AdditionalProperties = src.AdditionalProperties
	return
}
