// Code generated by structmap; DO NOT EDIT.
package main

import (
	ref1 "github.com/dkowalsky92/structmap/examples/simple/models1"
	ref2 "github.com/dkowalsky92/structmap/examples/simple/models2"
)

// MapUserToUserDTO copies User → UserDTO
func MapUserToUserDTO(src ref1.User) (dst ref2.UserDTO) {
	dst.ID = src.ID
	dst.Name = src.Name
	dst.Age = src.Age
	dst.Height = src.Height
	return
}
